config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "movies#index"
  # resources :reviews, only: [:destroy]
  get '/movies/filter_by', to: 'movies#index', as: :filtered_movies
  resources :movies do
    resources :reviews
    resources :likes
  end
  resources :users
  get '/signup', to: "users#new"
  resource :session, only: [:create]
  get '/signin', to: "sessions#new"
  get '/signout', to: 'sessions#destroy'

  # root 'movies#index'
  # get '/movies', to: 'movies#index'
  # get '/movies/new', to: 'movies#new'
  # get '/movies/:id', to: 'movies#show', as: :movie
  # post '/movies', to: 'movies#create'
  # get '/movies/:id/edit', to: 'movies#edit', as: :edit_movie
  # patch '/movies/:id', to: 'movies#update'
  # delete '/movies/:id', to: 'movies#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <%= image_tag 'logo.png' %>
  <%= link_to 'Released movies', filtered_movies_path(:type => "released"), class: "movie-filter" %>
  <%= link_to 'Upcoming movies', filtered_movies_path(:type => "upcoming"), class: "movie-filter" %>
  <%= link_to 'Recent movies', filtered_movies_path(:type => "recent"), class: "movie-filter" %>
  <% if current_user %>
    <%= link_to ' SignOut', signout_path, class:"account-settings" %>
    <%= link_to 'Account settings |', edit_user_path(current_user), class:"account-settings" %>
    <p class="account-settings">Hello <%= current_user.name %>!<span> &nbsp;|&nbsp; </span></p>
  <% else %>
    <p style="float:right"><%= link_to 'SignUp', signup_path, class:"signup" %></p>
    <p style="float:right"><%= link_to 'SignIn', signin_path, class:"signup" %></p>
  <% end %>
  </header>
  <div class="content">
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>
  <footer style="text-align:center">Copyrights to <a href="https://www.google.com" style="text-decoration:none">Flix.com</a> @ <%=Time.now.year%></footer>
  </body>
</html>